### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by LRW1** [Sehyn/CheatsGate-Discord-Raider#1]
Error log tells me that tokens.txt is missing. Creating an empty "tokens.txt" file won't solve this. So, how can I solve this ? Any help appreciated.

`************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'D:\Downloads\CheatsGate-Discord-Raider-master\CheatsGate - Discord Raider\bin\Release\tokens.txt'.
File name: 'D:\Downloads\CheatsGate-Discord-Raider-master\CheatsGate - Discord Raider\bin\Release\tokens.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at CheatsGate___Discord_Raider.Raider.MaterialFlatButton1_Click(Object sender, EventArgs e) in D:\Downloads\CheatsGate-Discord-Raider-master\CheatsGate - Discord Raider\Raider.cs:line 82
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Sehyn** [comment]
Sorry, I must have put this in the _readme.md_
So actually, in order to load your bots AKA tokens.
You need to create a tokens.txt file where the executable is.
Then all you have to do is copy those tokens on that text file and save it.

If you're looking to get tokens, well you can either buy them from: https://shoppy.gg/@Passive (this is where I got mine he is 100% legit)
 
Or you can make Tokens grabbers, or simply create yourself accounts and get their tokens.

![image](https://user-images.githubusercontent.com/48888351/60383637-cd6e8680-9a73-11e9-9de0-8f664ce3915a.png)
